/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selenium_docker_validation;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;


import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import static org.assertj.core.api.Assumptions.assumeThat;
import static org.assertj.core.api.Assertions.*;

class ChromeStandaloneTest {

    WebDriver driver;

    boolean isOnline(URL url) throws IOException {
        HttpURLConnection connection = (HttpURLConnection)url.openConnection();
        return connection.getResponseCode() == 200;
    }

    @BeforeEach
    void before() throws IOException {
        URL seleniumServerURL = new URL("http://localhost:4444/");
        assumeThat(isOnline(seleniumServerURL)).isTrue();
        ChromeOptions options = new ChromeOptions();
        driver = new RemoteWebDriver(seleniumServerURL, options);
        System.out.println("WebDriver initialized");
    }

    @Test 
    void appHasAGreeting() throws InterruptedException {
        driver.get("https://bonigarcia.dev/selenium-webdriver-java/");
        assertThat(driver.getTitle()).contains("Selenium WebDriver");
    }

    @AfterEach
    void after() {
        driver.quit();
    }
}
